In [21]:
import pandas as pd

In [22]:
import numpy as np
import seaborn as sns

In [23]:
df=pd.read_csv("./CSVs/cars.csv")
df.describe()

          km_driven  selling_price
count  8.128000e+03   8.128000e+03
mean   6.981951e+04   6.382718e+05
std    5.655055e+04   8.062534e+05
min    1.000000e+00   2.999900e+04
25%    3.500000e+04   2.549990e+05
50%    6.000000e+04   4.500000e+05
75%    9.800000e+04   6.750000e+05
max    2.360457e+06   1.000000e+07

In [24]:
df.sample(5)

           brand  km_driven    fuel         owner  selling_price
6791      Maruti      40000  Petrol   First Owner         250000
3426       Volvo       2000  Diesel   First Owner        2475000
6130        Tata      50000  Diesel   Third Owner         180000
3378  Ambassador      90000  Diesel  Second Owner          75000
1674  Volkswagen      97000  Diesel   First Owner        1350000

In [25]:
df['owner'].value_counts(), df[['fuel']].value_counts(),

(owner
 First Owner             5289
 Second Owner            2105
 Third Owner              555
 Fourth & Above Owner     174
 Test Drive Car             5
 Name: count, dtype: int64,
 fuel
 Diesel    4402
 Petrol    3631
 CNG         57
 LPG         38
 Name: count, dtype: int64)

# One hot Encoding using PANDAS

In [26]:
pd.get_dummies(df,columns=['owner','fuel'],dtype=np.int32)

,brand,km_driven,selling_price,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol
0,Maruti,145500,450000,1,0,0,0,0,0,1,0,0
1,Skoda,120000,370000,0,0,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,1,0,0
4,Maruti,120000,130000,1,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,1,0,0,0,0,0,0,0,1
8124,Hyundai,119000,135000,0,1,0,0,0,0,1,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,1,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,1,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,1,0,0

In [27]:
pd.get_dummies(df,columns=['owner','fuel'],dtype=np.int32,drop_first='first')

,brand,km_driven,selling_price,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,fuel_Diesel,fuel_LPG,fuel_Petrol
0,Maruti,145500,450000,0,0,0,0,1,0,0
1,Skoda,120000,370000,0,1,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,1
3,Hyundai,127000,225000,0,0,0,0,1,0,0
4,Maruti,120000,130000,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,0,0,0,1
8124,Hyundai,119000,135000,1,0,0,0,1,0,0
8125,Maruti,120000,382000,0,0,0,0,1,0,0
8126,Tata,25000,290000,0,0,0,0,1,0,0
8127,Tata,25000,290000,0,0,0,0,1,0,0

# One hot Encoding using SKLEARN.PREPROCESSING

In [38]:
X=df.iloc[:,0:4]
Y=df.iloc[:,-1]

In [39]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)

In [40]:
from sklearn.preprocessing import OneHotEncoder

In [52]:
ohe=OneHotEncoder(drop="first",sparse_output=True)

In [54]:
ohe.fit_transform(x_train[['fuel','owner']])

<6502x7 sparse matrix of type '<class 'numpy.float64'>'
	with 8722 stored elements in Compressed Sparse Row format>

In [55]:
np.array(df[['brand','km_driven']])

array([['Maruti', 145500],
       ['Skoda', 120000],
       ['Honda', 140000],
       ...,
       ['Maruti', 120000],
       ['Tata', 25000],
       ['Tata', 25000]], dtype=object)

In [56]:
pd.DataFrame(np.hstack((np.array(x_train[['brand','km_driven']]),ohe.transform(x_train[['fuel','owner']]).toarray())))

              0       1    2    3    4    5    6    7    8
0        Maruti  120000  0.0  0.0  1.0  0.0  0.0  0.0  1.0
1          Jeep    5000  0.0  0.0  1.0  0.0  0.0  0.0  0.0
2        Maruti   35000  0.0  0.0  1.0  0.0  0.0  0.0  0.0
3       Hyundai   60000  1.0  0.0  0.0  0.0  0.0  0.0  0.0
4          Tata  120000  1.0  0.0  0.0  1.0  0.0  0.0  0.0
...         ...     ...  ...  ...  ...  ...  ...  ...  ...
6497       Ford   40000  1.0  0.0  0.0  0.0  0.0  0.0  0.0
6498      Honda   60000  1.0  0.0  0.0  0.0  1.0  0.0  0.0
6499    Hyundai   90000  1.0  0.0  0.0  0.0  1.0  0.0  0.0
6500  Chevrolet   70000  0.0  1.0  0.0  0.0  0.0  0.0  0.0
6501       Tata   80000  1.0  0.0  0.0  0.0  0.0  0.0  0.0

[6502 rows x 9 columns]

In [57]:
pd.DataFrame(np.hstack((np.array(x_test[['brand','km_driven']]),ohe.transform(x_test[['fuel','owner']]).toarray())))

              0      1    2    3    4    5    6    7    8
0        Maruti  80000  1.0  0.0  0.0  0.0  1.0  0.0  0.0
1        Toyota  80000  1.0  0.0  0.0  0.0  1.0  0.0  0.0
2       Hyundai  30000  0.0  0.0  1.0  0.0  0.0  0.0  0.0
3         Honda  85000  0.0  0.0  1.0  0.0  1.0  0.0  0.0
4       Hyundai   4337  0.0  0.0  1.0  0.0  0.0  0.0  0.0
...         ...    ...  ...  ...  ...  ...  ...  ...  ...
1621       Ford  48000  1.0  0.0  0.0  0.0  1.0  0.0  0.0
1622    Hyundai  80000  1.0  0.0  0.0  0.0  1.0  0.0  0.0
1623    Renault  28000  0.0  0.0  1.0  0.0  0.0  0.0  0.0
1624        BMW   7500  1.0  0.0  0.0  0.0  0.0  0.0  0.0
1625  Chevrolet  30000  0.0  0.0  1.0  0.0  0.0  0.0  0.0

[1626 rows x 9 columns]

# One hot Encoding for many Catogories

In [58]:
count=df.brand.value_counts()

In [67]:
count

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [65]:
repl=count[count<=100].index

In [66]:
repl

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Force', 'Land', 'Isuzu', 'Kia',
       'Ambassador', 'Daewoo', 'MG', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [78]:
df['brand'].replace(repl,"Uncommon",inplace=True)

In [85]:
df['brand'].value_counts()

brand
Maruti        2448
Hyundai       1415
Mahindra       772
Tata           734
Uncommon       538
Toyota         488
Honda          467
Ford           397
Chevrolet      230
Renault        228
Volkswagen     186
BMW            120
Skoda          105
Name: count, dtype: int64

In [79]:
pd.get_dummies(df['brand'],dtype=np.int32)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Uncommon,Volkswagen
0,0,0,0,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,1,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,0,0,0,0,1,0,0,0,0,0,0,0,0
8124,0,0,0,0,1,0,0,0,0,0,0,0,0
8125,0,0,0,0,0,0,1,0,0,0,0,0,0
8126,0,0,0,0,0,0,0,0,0,1,0,0,0
8127,0,0,0,0,0,0,0,0,0,1,0,0,0

In [86]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [88]:
ohe.fit_transform(df[['brand']]).toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])