In [1]:
from sklearn.compose import ColumnTransformer

In [2]:
import pandas as pd 
import numpy as np

In [3]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer

In [4]:
import pandas as pd

In [5]:
df=pd.read_csv("./CSVs/covid_toy.csv")

# by using old method

In [6]:
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [9]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [22]:
df.describe()

              age       fever
count  100.000000   90.000000
mean    44.220000  100.844444
std     24.878931    2.054926
min      5.000000   98.000000
25%     20.000000   99.000000
50%     45.000000  101.000000
75%     66.500000  102.750000
max     84.000000  104.000000

In [12]:
age=df.drop(['gender','fever','cough','city','has_covid'],axis=1).values

In [19]:
ohe=OneHotEncoder(drop="first",sparse_output=False)
gender=ohe.fit_transform(df[['gender']])

In [44]:
si=SimpleImputer()
fever=si.fit_transform(df[['fever']])

In [30]:
od=OrdinalEncoder(categories=[["Mild","Strong"]])

In [31]:
cough=od.fit_transform(df[['cough']])

In [21]:
city=ohe.fit_transform(df[['city']])

In [32]:
X=pd.DataFrame(np.concatenate((age,gender,fever,cough,city),axis=1))

In [33]:
X

       0    1      2    3    4    5    6
0   60.0  1.0  103.0  0.0  0.0  1.0  0.0
1   27.0  1.0  100.0  0.0  1.0  0.0  0.0
2   42.0  1.0  101.0  0.0  1.0  0.0  0.0
3   31.0  0.0   98.0  0.0  0.0  1.0  0.0
4   65.0  0.0  101.0  0.0  0.0  0.0  1.0
..   ...  ...    ...  ...  ...  ...  ...
95  12.0  0.0  104.0  0.0  0.0  0.0  0.0
96  51.0  0.0  101.0  1.0  0.0  1.0  0.0
97  20.0  0.0  101.0  0.0  0.0  0.0  0.0
98   5.0  0.0   98.0  1.0  0.0  0.0  1.0
99  10.0  0.0   98.0  1.0  0.0  1.0  0.0

[100 rows x 7 columns]

# From Column Transfomer

In [39]:
ct=ColumnTransformer(transformers=[
    ('for_gender',OneHotEncoder(drop="first",sparse_output=False),['gender']),
    ('for_fever',SimpleImputer(),['fever']),
    ('for_cough',OrdinalEncoder(categories=[['Mild',"Strong"]]),['cough']),
    ('for_city',OneHotEncoder(drop="first",sparse_output=False),['city']),
],remainder="passthrough")

In [40]:
X_ct=ct.fit_transform(df)

In [42]:
pd.DataFrame(X_ct)

      0      1    2    3    4    5   6    7
0   1.0  103.0  0.0  0.0  1.0  0.0  60   No
1   1.0  100.0  0.0  1.0  0.0  0.0  27  Yes
2   1.0  101.0  0.0  1.0  0.0  0.0  42   No
3   0.0   98.0  0.0  0.0  1.0  0.0  31   No
4   0.0  101.0  0.0  0.0  0.0  1.0  65   No
..  ...    ...  ...  ...  ...  ...  ..  ...
95  0.0  104.0  0.0  0.0  0.0  0.0  12   No
96  0.0  101.0  1.0  0.0  1.0  0.0  51  Yes
97  0.0  101.0  0.0  0.0  0.0  0.0  20   No
98  0.0   98.0  1.0  0.0  0.0  1.0   5   No
99  0.0   98.0  1.0  0.0  1.0  0.0  10  Yes

[100 rows x 8 columns]